services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    command: start-dev --import-realm
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: ""
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-demo.json:/opt/keycloak/data/import/realm-demo.json:ro
    ports:
      - "8080:8080"