server:
  port: 8080
springdoc:
  packages-to-scan: com.kadri.resilience4j

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      enabled: true

  timelimiter:
    instances:
      timeLimiterApi:
        timeout-duration: 2s
        cancel-running-future: true
    metrics:
      enabled: true

  bulkhead:
    instances:
      bulkheadApi:
        max-concurrent-calls: 3
        max-wait-duration: 1ms
    metrics:
      enabled: true

  ratelimiter:
    instances:
      rateLimiterApi:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
        register-health-indicator: true
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50
    metrics:
      enabled: true